### ISSUE TITLE
【Phase 4-2】AWSデプロイメント・インフラ構築

### ISSUE THREAD

**Issue by sakamo-wni** [sakamo-wni/MobileCommentGenerator#11]
# 概要

**優先度: 10**  
**推奨開発順序: 10番目（最終段階）**  
**想定工数: 4-5日**  
**依存: Issue #7-9 (全コア機能完成)**

AWSクラウドへのシステムデプロイと本番環境インフラ構築を行います。Lambda/ECS、S3、CloudWatchを活用したスケーラブルな運用環境を構築します。

## 背景

- READMEでAWSデプロイメントが言及されている
- S3での過去コメントデータ管理が既に前提となっている
- 本番環境での安定運用とスケーラビリティが必要

### 必須機能

1. **Lambda/ECSでのAPI化**
   ```python
   # lambda_handler.py (Lambda使用の場合)
   import json
   from workflows.comment_generation_workflow import create_comment_generation_workflow
   
   def lambda_handler(event, context):
       try:
           workflow = create_comment_generation_workflow()
           result = workflow.invoke(json.loads(event['body']))
           
           return {
               'statusCode': 200,
               'headers': {'Content-Type': 'application/json'},
               'body': json.dumps(result)
           }
       except Exception as e:
           return {
               'statusCode': 500,
               'body': json.dumps({'error': str(e)})
           }
   ```

2. **CloudFormation/Terraformテンプレート**
   ```yaml
   # cloudformation/main.yaml
   AWSTemplateFormatVersion: '2010-09-09'
   Description: '天気コメント生成システム'
   
   Parameters:
     Environment:
       Type: String
       Default: production
       AllowedValues: [development, staging, production]
   
   Resources:
     CommentGenerationFunction:
       Type: AWS::Lambda::Function
       Properties:
         FunctionName: !Sub '${Environment}-comment-generator'
         Runtime: python3.10
         Handler: lambda_handler.lambda_handler
         Code:
           S3Bucket: !Ref DeploymentBucket
           S3Key: lambda-deployment.zip
   ```

3. **Docker化**
   ```dockerfile
   # Dockerfile
   FROM python:3.10-slim
   
   WORKDIR /app
   
   # 依存関係インストール
   COPY requirements.txt .
   RUN pip install --no-cache-dir -r requirements.txt
   
   # アプリケーションコピー
   COPY src/ ./src/
   COPY config/ ./config/
   
   # Lambdaランタイムまたはウェブサーバー
   EXPOSE 8000
   CMD [\"uvicorn\", \"src.api.main:app\", \"--host\", \"0.0.0.0\", \"--port\", \"8000\"]
   ```

### 実装ファイル
- `infrastructure/cloudformation/` (CloudFormationテンプレート)
- `infrastructure/terraform/` (Terraformファイル)
- `deploy/` (デプロイスクリプト)
- `Dockerfile` (コンテナ化)
- `.github/workflows/` (CI/CDパイプライン)

#### コンピューティング層
- **AWS Lambda**: コメント生成API (軽量・イベント駆動)
- **または Amazon ECS**: 高負荷・継続処理用 (コンテナベース)
- **API Gateway**: REST API エンドポイント

#### ストレージ層
- **Amazon S3**: 
  - 過去コメントJSONLファイル (`it-literacy-457604437098-ap-northeast-1`)
  - 設定ファイル・プロンプトテンプレート
  - フロントエンド静的ファイル (React UI使用時)

#### ネットワーク・セキュリティ
- **CloudFront**: CDN配信・キャッシング
- **ALB**: ECS使用時のロードバランサー
- **VPC**: ネットワーク分離
- **IAM**: 最小権限の原則

#### 監視・ログ
- **CloudWatch**: メトリクス・ログ監視
- **X-Ray**: 分散トレーシング
- **SNS**: アラート通知

#### 1. Lambdaベースアーキテクチャ（推奨）
```bash
# デプロイスクリプト例
#!/bin/bash
set -e

# 依存関係パッケージング
pip install -r requirements.txt -t package/
cp -r src/ package/
cd package && zip -r ../lambda-deployment.zip . && cd ..

# CloudFormationデプロイ
aws cloudformation deploy \
  --template-file infrastructure/cloudformation/main.yaml \
  --stack-name weather-comment-generator-prod \
  --parameter-overrides Environment=production \
  --capabilities CAPABILITY_IAM

# Lambdaコード更新
aws lambda update-function-code \
  --function-name production-comment-generator \
  --zip-file fileb://lambda-deployment.zip
```

#### 2. ECSベースアーキテクチャ（高負荷対応）
```yaml
# docker-compose.yml (開発時)
version: '3.8'
services:
  app:
    build: .
    ports:
      - \"8000:8000\"
    environment:
      - AWS_DEFAULT_REGION=ap-northeast-1
      - S3_COMMENT_BUCKET=it-literacy-457604437098-ap-northeast-1
    volumes:
      - ~/.aws:/root/.aws:ro
```

### GitHub Actions
```yaml
# .github/workflows/deploy.yml
name: Deploy to AWS

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run tests
        run: pytest tests/ --cov=src/ --cov-report=xml
      
      - name: Upload coverage
        uses: codecov/codecov-action@v3

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Deploy to AWS
        run: |
          chmod +x deploy/deploy.sh
          ./deploy/deploy.sh production
```

### 開発・ステージング・本番環境
```bash
# 環境別設定
export ENVIRONMENT=production
export AWS_REGION=ap-northeast-1
export S3_COMMENT_BUCKET=it-literacy-457604437098-ap-northeast-1
export LAMBDA_MEMORY_SIZE=1024
export LAMBDA_TIMEOUT=30
export API_GATEWAY_STAGE=v1
```

### 設定管理
```python
# config/aws_config.py
import os
from typing import Dict, Any

class AWSConfig:
    def __init__(self, environment: str = 'production'):
        self.environment = environment
        self.region = os.getenv('AWS_REGION', 'ap-northeast-1')
        self.s3_bucket = os.getenv('S3_COMMENT_BUCKET')
        
    def get_lambda_config(self) -> Dict[str, Any]:
        return {
            'memory_size': int(os.getenv('LAMBDA_MEMORY_SIZE', '1024')),
            'timeout': int(os.getenv('LAMBDA_TIMEOUT', '30')),
            'environment_variables': {
                'ENVIRONMENT': self.environment,
                'S3_COMMENT_BUCKET': self.s3_bucket
            }
        }
```

## 受け入れ条件

- [ ] AWSインフラの正常構築
- [ ] Lambda/ECS でのAPI正常動作
- [ ] S3からの過去コメント取得動作
- [ ] CloudWatch でのログ・メトリクス監視
- [ ] CI/CDパイプラインの正常動作
- [ ] 本番環境での負荷テスト合格
- [ ] セキュリティ監査の合格
- [ ] 災害復旧手順の文書化

### CloudWatchメトリクス
- **API応答時間**: 平均・P95・P99
- **エラー率**: 4xx/5xx レスポンス率
- **Lambda実行時間**: 実行時間・メモリ使用量
- **S3アクセス**: 取得成功率・レイテンシ

### アラート設定
```python
# monitoring/cloudwatch_alarms.py
import boto3

def create_alarms():
    cloudwatch = boto3.client('cloudwatch')
    
    # API エラー率アラート
    cloudwatch.put_metric_alarm(
        AlarmName='CommentGenerator-HighErrorRate',
        ComparisonOperator='GreaterThanThreshold',
        EvaluationPeriods=2,
        MetricName='4XXError',
        Namespace='AWS/ApiGateway',
        Period=300,
        Statistic='Sum',
        Threshold=10.0,
        ActionsEnabled=True,
        AlarmActions=['arn:aws:sns:ap-northeast-1:123456789012:alerts']
    )
```

### IAM権限最小化
```json
{
  \"Version\": \"2012-10-17\",
  \"Statement\": [
    {
      \"Effect\": \"Allow\",
      \"Action\": [
        \"s3:GetObject\"
      ],
      \"Resource\": \"arn:aws:s3:::it-literacy-457604437098-ap-northeast-1/*\"
    },
    {
      \"Effect\": \"Allow\",
      \"Action\": [
        \"logs:CreateLogGroup\",
        \"logs:CreateLogStream\",
        \"logs:PutLogEvents\"
      ],
      \"Resource\": \"*\"
    }
  ]
}
```

### API認証・認可
- API Keyによるアクセス制御
- レート制限の実装
- CORS設定の適切な構成

### 想定コスト（月間）
- **Lambda**: $10-50 (1000リクエスト/日想定)
- **S3**: $5-20 (データストレージ・転送)
- **CloudWatch**: $5-15 (ログ・メトリクス)
- **API Gateway**: $3-10 (API呼び出し)

### 最適化施策
- Lambda コールドスタート対策
- S3 インテリジェント階層化
- CloudWatch ログ保持期間最適化
