### ISSUE TITLE
【要件調整】LangGraphワークフロー実装の加速と依存関係の整理

### ISSUE THREAD

**Issue by sakamo-wni** [sakamo-wni/MobileCommentGenerator#17]
# 概要

要件文書（README）との整合性を確保するため、LangGraphワークフローの実装を加速する必要があります。

## 現状の課題

1. **LangGraphワークフロー統合（Issue #7）の優先度向上**
   - 現在優先度6となっているが、要件ではLangGraphが中心的な技術として位置づけられている
   - Issue #5, #6の実装前にワークフローの基本構造を確立すべき

2. **依存関係の再整理**
   - 現在：個別ノード実装 → ワークフロー統合
   - 推奨：ワークフロー骨格 → 個別ノード実装・統合

### 1. 実装順序の変更
1. Issue #7（LangGraphワークフロー）の基本実装を先行
2. Issue #5, #6を並行して実装し、完成次第ワークフローに統合
3. 各ノードは最初はモック実装で動作確認

### 2. LangGraphワークフローの段階的実装
```python
# Phase 1: 基本的なワークフロー骨格
workflow = StateGraph(CommentGenerationState)
workflow.add_node("input", mock_input_node)
workflow.add_node("fetch_forecast", fetch_forecast_node)  # 実装済み
workflow.add_node("retrieve_comments", retrieve_past_comments_node)  # 実装済み
workflow.add_node("select_pair", mock_select_pair_node)  # モック
workflow.add_node("evaluate", mock_evaluate_node)  # モック
workflow.add_node("generate", generate_comment_node)  # 実装済み
workflow.add_node("output", mock_output_node)  # モック

# Phase 2: 各ノードの実装と統合
# Issue #5, #6の完成に応じて順次置き換え
```

### 3. 表現ルール実装の具体化
```yaml
# config/expression_rules.yaml
ng_words:
  disaster: ["災害", "危険", "警報", "緊急"]
  negative: ["最悪", "ひどい", "つらい"]
  
character_limit: 15
min_characters: 5

validation_rules:
  - no_special_characters
  - appropriate_tone
  - weather_relevance
```

## アクションアイテム

- [ ] Issue #7の優先度を上げ、基本実装を開始
- [ ] モックノードを含むワークフローのEnd-to-Endテストを作成
- [ ] 表現ルール設定ファイルの作成
- [ ] READMEの更新（現状との整合性確保）

## 関連Issue

- #5 コメント選択・類似度計算機能
- #6 コメント評価・バリデーション機能
- #7 LangGraphワークフロー統合
