### ISSUE TITLE
【Phase 3-3】Streamlit UI統合テスト実装

### ISSUE THREAD

**Issue by sakamo-wni** [sakamo-wni/MobileCommentGenerator#32]
# 概要

**優先度: 9**  
**推奨開発順序: 10番目**  
**想定工数: 1-2日**  
**依存: Issue #9 (Streamlit UI実装)**

Streamlit UIの統合テストを実装し、ワークフローとの統合動作を検証します。

## 背景

- StreamlitアプリケーションのUI実装は完了（app.py, streamlit_components.py, streamlit_utils.py）
- Phase 2でワークフロー統合が完了
- UIとワークフローの統合テストが未実装
- Streamlit 1.28+から利用可能な`streamlit.testing`フレームワークを活用

### 必須機能

1. **AppTestを使用した統合テスト**
   ```python
   # tests/test_streamlit_app.py
   from streamlit.testing.v1 import AppTest
   
   def test_comment_generation_flow():
       """コメント生成の完全なフローをテスト"""
       at = AppTest.from_file("app.py")
       at.run()
       
       # 地点選択
       at.selectbox[0].select("東京").run()
       
       # LLMプロバイダー選択
       at.selectbox[1].select("openai").run()
       
       # 生成ボタンクリック
       at.button[0].click().run()
       
       # 結果確認
       assert at.success[0].value is not None
   ```

2. **モックを使用したAPI/ワークフローテスト**
   - 外部API呼び出しのモック
   - ワークフロー実行のモック
   - エラーシナリオのテスト

3. **UIコンポーネントテスト**
   - 地点選択機能のテスト
   - LLMプロバイダー選択のテスト
   - 結果表示・コピー機能のテスト
   - 履歴表示のテスト

### 実装ファイル
- `tests/test_streamlit_app.py` (メインアプリテスト)
- `tests/test_streamlit_components.py` (コンポーネントテスト)
- `tests/test_streamlit_utils.py` (ユーティリティテスト)
- `.github/workflows/ui-tests.yml` (CI/CD設定)

#### 1. 基本的なアプリ起動テスト
```python
def test_app_loads_without_errors():
    """アプリが正常に起動することを確認"""
    at = AppTest.from_file("app.py")
    at.run()
    assert not at.exception
    assert "天気コメント生成システム" in at.markdown[0].value
```

#### 2. インタラクションテスト
```python
def test_location_selection():
    """地点選択が正しく動作することを確認"""
    at = AppTest.from_file("app.py")
    at.run()
    
    # 初期状態の確認
    assert at.selectbox[0].value == "東京"
    
    # 地点変更
    at.selectbox[0].select("大阪").run()
    assert at.session_state["selected_location"] == "大阪"
```

#### 3. ワークフロー統合テスト
```python
@patch('src.workflows.comment_generation_workflow.run_comment_generation')
def test_comment_generation_integration(mock_run):
    """ワークフローとの統合をテスト"""
    # モックの設定
    mock_run.return_value = {
        'success': True,
        'final_comment': 'テストコメント',
        'generation_metadata': {'location': '東京'}
    }
    
    at = AppTest.from_file("app.py")
    at.run()
    at.button[0].click().run()
    
    # 成功メッセージの確認
    assert "コメント生成が完了しました" in at.success[0].value
    assert "テストコメント" in at.markdown[-1].value
```

### エラーハンドリングテスト

```python
def test_error_handling():
    """エラー時の適切な表示を確認"""
    with patch('src.workflows.comment_generation_workflow.run_comment_generation') as mock:
        mock.return_value = {
            'success': False,
            'error': 'API接続エラー',
            'final_comment': None
        }
        
        at = AppTest.from_file("app.py")
        at.run()
        at.button[0].click().run()
        
        assert "生成に失敗しました" in at.error[0].value
```

### セッション状態テスト

```python
def test_session_state_persistence():
    """セッション状態が正しく保持されることを確認"""
    at = AppTest.from_file("app.py")
    at.run()
    
    # 初期状態
    assert at.session_state["selected_location"] == "東京"
    assert at.session_state["llm_provider"] == "openai"
    
    # 状態変更
    at.selectbox[0].select("稚内").run()
    at.selectbox[1].select("gemini").run()
    
    # 変更後の確認
    assert at.session_state["selected_location"] == "稚内"
    assert at.session_state["llm_provider"] == "gemini"
```

## 受け入れ条件

- [ ] 全てのUIコンポーネントがテストでカバーされている
- [ ] ワークフローとの統合が正しくテストされている
- [ ] エラーシナリオが適切にテストされている
- [ ] テストカバレッジ80%以上
- [ ] CI/CDパイプラインでテストが自動実行される
- [ ] モックを使用して外部依存を排除

### GitHub Actions設定例
```yaml
name: Streamlit UI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov
      
      - name: Run UI tests
        run: |
          pytest tests/test_streamlit*.py -v --cov=src/ui --cov-report=html
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
```

## パフォーマンステスト

- ページ読み込み時間の測定
- 大量データでの応答性確認
- メモリ使用量の監視

## 開発のヒント

1. **テスト実行の高速化**
   - `@st.cache_data`のモック化
   - 不要な`time.sleep`の削除
   
2. **デバッグ方法**
   - `at.exception`で例外を確認
   - `print(at)`でアプリの現在状態を出力

3. **ベストプラクティス**
   - 各テストは独立して実行可能に
   - 適切なsetup/teardownの実装
   - 意味のあるテスト名の使用

## 参考リンク

- [Streamlit App Testing Documentation](https://docs.streamlit.io/develop/concepts/app-testing)
- [pytest Documentation](https://docs.pytest.org/)
- [Python unittest.mock](https://docs.python.org/3/library/unittest.mock.html)
